# Generated by Django 3.2.5 on 2021-09-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_prdouctgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prdouctgallery',
            options={'verbose_name': 'Product gallery', 'verbose_name_plural': 'Product gallery'},
        ),
    ]
