# Generated by Django 3.2.5 on 2022-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_prdouctgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photos/products/no_img_avaliable.jpg', upload_to='photos/products'),
        ),
    ]
