# Generated by Django 3.2.5 on 2022-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='photos/products/no_img_avaliable.jpg', upload_to='photos/products'),
        ),
    ]
